name: GPU Price Tracker

on:
  schedule:
    - cron: '*/5 * * * *' # Ab yeh har 5 minute me chalne ke liye queue me lagega
  workflow_dispatch: 

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install requests beautifulsoup4

    - name: Run Tracker Script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python tracker.py
